name: "CTR Sim"
time-step: 5e-4
end-time: 5 

hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: True

objects:
  - 
    type: "CTR"
    name: "ctr"
    num-bodies: 1
    initial-angle: 60
    projector-type: "block"
    render-type: "PBR"
    # orm-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_ORM.png"
    # base-color-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_Color.png"
    metallic: 0.2
    roughness: 0.5
    color: [1.0, 1.0, 1.0]