name: "Pendulum Sim"
time-step: 1e-3
end-time: 10

logging: True
logging-output-folder: "../output/pendulum"
logging-interval: 1e-1
log-residuals: True


hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: True

objects:
  - 
    type: "Pendulum"
    name: "pendulum"
    num-bodies: 1
    initial-angle: 100
    projector-type: "block"
    render-type: "PBR"
    # orm-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_ORM.png"
    # base-color-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_Color.png"
    metallic: 0.2
    roughness: 0.5
    color: [1.0, 1.0, 1.0]