name: "Plane-Box Friction"
# sim-mode: "Frame-by-frame"
time-step: 1e-3
end-time: 100
solver-iters: 1

hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: True

objects:
  - 
    type: "RigidBox"
    name: "box1"
    initial-position: [0, 0.35, 0.0]
    initial-rotation: [0, 0, 0]
    initial-velocity: [0, 0, 2]
    size: [0.5,0.5,0.5]
    render-type: "PBR"
    # orm-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_ORM.png"
    # base-color-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_Color.png"
    metallic: 0.0
    roughness: 0.5
    color: [1.0, 0.0, 0.0]

  - 
    type: "RigidBox"
    name: "box2"
    initial-position: [0, 0.05, 0.0]
    initial-rotation: [0, 0, 0]
    initial-velocity: [0, 0, 3]
    size: [1,0.1,1]
    render-type: "PBR"
    # orm-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_ORM.png"
    # base-color-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_Color.png"
    metallic: 0.0
    roughness: 0.5
    color: [0.0, 0.0, 1.0]

  # - 
  #   type: "RigidBox"
  #   name: "box2"
  #   initial-position: [0, 3, 0.0]
  #   initial-rotation: [0, 0, 0]
  #   size: [0.3,0.3,0.3]
  #   render-type: "PBR"
  #   # orm-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_ORM.png"
  #   # base-color-texture-filename: "../resource/textures/Metal050A_4K-PNG/Metal050A_4K-PNG_Color.png"
  #   metallic: 0.0
  #   roughness: 0.5
  #   color: [0, 0.0, 1.0]